#!/usr/bin/env bash
# Display content of the file /etc/passwd
while IFS=: read -r username _ uid _ _ home _
do
    # Displaying username, user id, and home directory path
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "-------------------------------------"
done < /etc/passwd