#!/usr/bin/env bash
# This script is displaying numbers from 1-20 times
counter=0
while [ $counter -le 20 ]
do
    if [ $counter -eq 4 ]
    then
        echo "$counter"
        echo 'bad luck from China'
    elif [ $counter -eq 9 ]
    then
        echo "$counter"
        echo 'bad luck from Japan'    
    elif [ $counter -eq 17 ]
    then
        echo "$counter"
        echo 'bad luck from Italy'
    else
        echo "$counter"
    fi
    ((counter++))
done


    


