#!/usr/bin/env bash
# Display time for 12 hours and 59 minutes
hour=0
echo "Hour: 0"
while [ $hour -le 12 ]
do
    minute=1
    #echo "Hour: 1"
    while [ $minute -le 59 ]
    do
        if [ $minute -eq 59 ]
        then
            echo "Hour: 1"
        fi
        echo "$minute"
        ((minute++))
    done
    echo "$hour"
    ((hour++))
done


