#!/usr/bin/env bash
# Check if running as root
if [ "$(id -u)" -ne 0 ]
then
    echo "Please run this script as root"
    exit 1
fi

# Backup existing hosts file
cp /etc/hosts /etc/hosts.bak

# Update hosts file
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Hosts file configured successfully."
